export const userConstants = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	LOGOUT: 'USERS_LOGOUT',
};

export const homeworkListConstants = {
	HOMEWORK_LIST_REQUEST: 'HOMEWORK_LIST_REQUEST',
	HOMEWORK_LIST_SUCCESS: 'HOMEWORK_LIST_SUCCESS',
	HOMEWORK_LIST_FAILURE: 'HOMEWORK_LIST_FAILURE',
};

export const homeworkConstants = {
	HOMEWORK_REQUEST: 'HOMEWORK_REQUEST',
	HOMEWORK_SUCCESS: 'HOMEWORK_SUCCESS',
	HOMEWORK_FAILURE: 'HOMEWORK_FAILURE',
};
