export const userConstants = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',

	CHANGE_PASSWORD_REQUEST : 'CHANGE_PASSWORD_REQUEST',
	CHANGE_PASSWORD_SUCCESS : 'CHANGE_PASSWORD_SUCCESS',
	CHANGE_PASSWORD_FAILURE : 'CHANGE_PASSWORD_FAILURE',

	LOGOUT: 'USERS_LOGOUT',
};

export const homeworkListConstants = {
	HOMEWORK_LIST_REQUEST: 'HOMEWORK_LIST_REQUEST',
	HOMEWORK_LIST_SUCCESS: 'HOMEWORK_LIST_SUCCESS',
	HOMEWORK_LIST_FAILURE: 'HOMEWORK_LIST_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const homeworkConstants = {
	HOMEWORK_REQUEST: 'HOMEWORK_REQUEST',
	HOMEWORK_SUCCESS: 'HOMEWORK_SUCCESS',
	HOMEWORK_FAILURE: 'HOMEWORK_FAILURE',
	ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
	ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
	ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

	REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
	REMOVE_TASK_FAILURE: 'REMOVE_TASK_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const uiConstants = {
	ADD_SUCCESS_SNACKBAR: 'ADD_SUCCESS_SNACKBAR',
	ADD_ERROR_SNACKBAR: 'ADD_ERROR_SNACKBAR',
	SNACKBAR_CLEAR: 'SNACKBAR_CLEAR',
};

export const solutionListConstants = {
	SOLUTION_LIST_REQUEST: 'SOLUTION_LIST_REQUEST',
	SOLUTION_LIST_SUCCESS: 'SOLUTION_LIST_SUCCESS',
	SOLUTION_LIST_FAILURE: 'SOLUTION_LIST_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const solutionConstants = {
	SOLUTION_REQUEST: 'SOLUTION_REQUEST',
	SOLUTION_SUCCESS: 'SOLUTION_SUCCESS',
	SOLUTION_FAILURE: 'SOLUTION_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const studentListConstants = {
	STUDENT_LIST_REQUEST: 'STUDENT_LIST_REQUEST',
	STUDENT_LIST_SUCCESS: 'STUDENT_LIST_SUCCESS',
	STUDENT_LIST_FAILURE: 'STUDENT_LIST_FAILURE',

	ADD_STUDENT_TO_HOMEWORK_SUCCESS: 'ADD_STUDENT_TO_HOMEWORK_SUCCESS',
	ADD_STUDENT_TO_HOMEWORK_FAILURE: 'ADD_STUDENT_TO_HOMEWORK_FAILURE',
	CLEAR_STUDENT_LIST: 'CLEAR_STUDENT_LIST',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const addHomeworkConstants = {
	ADD_HOMEWORK_REQUEST: 'ADD_HOMEWORK_REQUEST',
	ADD_HOMEWORK_FAILURE: 'ADD_HOMEWORK_FAILURE',
	ADD_HOMEWORK_SUCCESS: 'ADD_HOMEWORK_SUCCESS',
	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const studentProfileConstants = {
	STUDENT_PROFILE_REQUEST: 'STUDENT_PROFILE_REQUEST',
	STUDENT_PROFILE_SUCCESS: 'STUDENT_PROFILE_SUCCESS',
	STUDENT_PROFILE_FAILURE: 'STUDENT_PROFILE_FAILURE',
	
	CLEAR_ERROR: 'CLEAR_ERROR',
};
